service:
  name: importservice
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 
        - 's3:ListBucket'
      Resource: 
        - 'arn:aws:s3:::colpachoques-bucket-imported'
    - Effect: 'Allow'
      Action: 
        - 's3:*'
      Resource: 
        - 'arn:aws:s3:::colpachoques-bucket-imported/*'

functions:
  importProductsFile:
    handler: import-products-file.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
  importSecondFileParser:
    handler: import-file-parser.importSecondFileParser
    events:
      - s3:
          bucket: colpachoques-bucket-imported
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true